name: learn-github-actions
run-name: ${{ github.actor }} is trying to pull a docker image!
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    container:
        image: softcat477/ci-jobs:latest
        env: 
          CELERY_JOB_QUEUE: None
          ADMIN_USER: rodan
          ADMIN_PASS: rodan
          DJANGO_DEBUG_MODE: False
          DJANGO_SECRET_KEY: localdev
          DJANGO_MEDIA_ROOT: /rodan/data/
          # You can specify multiple hosts with a comma
          DJANGO_ALLOWED_HOSTS: "*"
          DJANGO_ADMIN_URL: admin/
          IIPSRV_URL: http://localhost/fcgi-bin/iipsrv.fcgi/
          DJANGO_ACCESS_LOG: /code/Rodan/rodan.log
          DJANGO_DEBUG_LOG: /code/Rodan/database.log
          SERVER_HOST: :""
          # Celery Configuration
          C_FORCE_ROOT: true
          # Database Configuration
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_DB: rodan
          POSTGRES_USER: rodan
          POSTGRES_PASSWORD: rodan
          POSTGRES_DATABASE_LOGFILE: /code/Rodan/database.log
          # RabbitMQ Configuration
          RABBITMQ_URL: amqp://guest_user:guest_pass@rabbitmq:5672//
          RABBITMQ_DEFAULT_USER: guest_user
          RABBITMQ_DEFAULT_PASS: guest_pass
          # Redis Configuration
          REDIS_HOST: redis
          REDIS_PORT: 6379
          REDIS_DB: 0
    steps:
      #- uses: actions/checkout@v3
      - run: cd /
      - run: ls -la
      - run: python3 -V
      - name: Print POSTGRES variables
        run: |
          echo $POSTGRES_HOST
          echo $POSTGRES_PORT
