name: learn-github-actions
run-name: ${{ github.actor }} is trying to pull a docker image!
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    container:
        image: softcat477/ci-jobs:latest
    steps:
      #- uses: actions/checkout@v3
      - run: cd /
      - run: ls -la
      - run: python3 -V
